plugins:   
  - {name: static_map, type: "costmap_2d::StaticLayer"}
  - {name: obstacles, type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  - {name: layer, type: "simple_layer_namespace::SimpleLayer"}
publish_frequency: 1.0
footprint: [[-0.153, 0.1405], [0.153, 0.1405], [0.153, -0.1405], [-0.153, -0.1405], [-0.153, 0.1405]]
