local_costmap:

  footprint: [[-0.153, 0.1405], [0.153, 0.1405], [0.153, -0.1405], [-0.153, -0.1405], [-0.153, 0.1405]]

  global_frame: map # tb3_1/odom
  robot_base_frame: tb3_1/base_footprint
  static_map: false
  rolling_window: true

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5  

  static_map: false  
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05

  plugins:
          # - {name: simplelayer, type: "multibot_layer_namespace::MultibotLayer"}
          # - {name: gridlayer, type: "multibot_layer_namespace::GridLayer"}
      - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
      - {name: inflation, type: "costmap_2d::InflationLayer"}
  obstacle_layer:
      observation_sources: laser
      laser: {data_type: LaserScan, sensor_frame: tb3_1/base_scan, topic: /tb3_1/scan, marking: true, clearing: true, obstacle_range: 2.0, raytrace_range: 5.0}
 
 
  inflation:
        inflation_radius: 1.0
        cost_scaling_factor: 10 # larger number = lower cost elevation   
