plugins: 
  - {name: static_map, type: "costmap_2d::StaticLayer"}
  - {name: obstacles, type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  - {name: pathing, type: "simple_local_layer_namespace::DynamicLocalLayer"}
publish_frequency: 1.0
footprint: [[-0.153, 0.1405], [0.153, 0.1405], [0.153, -0.1405], [-0.153, -0.1405], [-0.153, 0.1405]]
global_frame: odom
robot_base_frame: base_link